### ISSUE TITLE
[License] 这个软件使用什么开源协议？

### ISSUE THREAD

**Issue by ghost** [Fuermohao/ScreenShot#1]
你好，我现在想需要使用您的 ScreenShot 用作我的项目中的截屏功能，
请问您的项目使用的是什么开源协议呢？

PS： 项目地址： 
https://github.com/lhy0403/Qv2ray
https://github.com/lhy0403/Qv2ray/issues/69#issuecomment-553351301

**Comment by Singein** [comment]
你好，很荣幸这个项目能为你带来价值。
这是我之前学习QT时的练手项目，如果需要协议的话，MIT吧

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Singein** [comment]
放心直接拿去用吧，我看了下，哪个时候写的东西还是很low的，你可以简单看看源码，自己再改改

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ghost** [comment]
非常感谢！
我对您的项目进行了一些修改，如果方便的话，我可以在贡献者列表中使用 Singein 吗？

**Comment by Singein** [comment]
哈哈，荣幸之至！

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ghost** [comment]
好的！
Thanks a lot！
